# Tarea 6 prep

In [1]:
import scipy.sparse as sp
from scipy.sparse.linalg import cg
import numpy as np
# !pip install vtk
from vtk import *

In [2]:
# load system
Aload = sp.load_npz('elasticity_matrix.npz')
bload = np.load('rhs.npy')
fd = np.load('freedofs.npy')

In [4]:
# Solve
Afree = Aload[fd,:][:,fd]
bfree = bload[fd]
xsol = np.zeros(bload.size, dtype=np.float64)
# Your solver
# xsol[fd], exit_code = PCGSOLVER(Afree, bfree, P = Gauss_Sidel, tol=1e-8)

## plotting

In [5]:
numpy_vertices = np.load('vertices.npy')
numpy_elements = np.load('elements.npy')

number_of_points = numpy_vertices.shape[0]
number_of_elements = numpy_elements.shape[0]

In [7]:
my_vtk_dataset = vtkUnstructuredGrid()
points = vtkPoints()
for id in range(number_of_points):
    points.InsertPoint(id, numpy_vertices[id,:])
my_vtk_dataset.SetPoints(points)

elements_type = VTK_TETRA
my_vtk_dataset.Allocate(number_of_elements)
for id in range(number_of_elements):
    point_ids = numpy_elements[id,:]
    my_vtk_dataset.InsertNextCell(elements_type, 4, point_ids)

array = vtkDoubleArray()
array.SetNumberOfComponents(3)
array.SetNumberOfTuples(number_of_points)
array.SetName('Displacement')
for id in range(number_of_points):
    values = [xsol[id], xsol[id+number_of_points], xsol[id+2*number_of_points]]
    array.SetTuple(id, values)
my_vtk_dataset.GetPointData().AddArray(array)

writer = vtkXMLUnstructuredGridWriter()
writer.SetFileName("tarea6_displacement.vtu")
writer.SetInputData(my_vtk_dataset)
writer.Write()

1

In [12]:
import numpy as np
A = np.array([[-1,-1,1],[1,-1,0],[0,2,-1]], dtype=np.float64)
xsol = np.array([-1,2,3], dtype=np.float64)
b = A.dot(xsol )

In [13]:
Ainv = np.linalg.pinv(A)
print(Ainv)

[[-0.38888889  0.44444444 -0.05555556]
 [-0.05555556 -0.22222222  0.27777778]
 [ 0.22222222 -0.11111111 -0.11111111]]


In [14]:
print(A@Ainv)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


In [17]:
x = Ainv.dot(b)
print(x)

[-2.16666667  0.83333333  0.66666667]


In [16]:
print(A.dot(x), b)

[ 2. -3.  1.] [ 2. -3.  1.]
