# Ayudantía 1

In [1]:
import numpy as np
import scipy.linalg as LA
import matplotlib.pyplot as plt

## Problema 1: Cómo evitar perdida de información por cancelación.

Queremos calcular las raíces del polinomio:

$$p(x)=x^{2}-56x + 1$$

Podemos calcular que sus raíces son:

$$x_{1,2}=28 \pm \sqrt{783}$$

Esta solución es la que se conoce como solución exacta. En particular, para calcularlas habrá que aproximar $\sqrt{783}$ por algún valor numérico. Tomaremos la siguiente aproximación como demostración:

$$\sqrt{783}\approx 27.982 (\pm 0.0001)$$

### Calcule los errores relativos que se obtienen con esta aproximación

In [2]:
raiz_1 = 28 + np.sqrt(783)
raiz_2 = 28 - np.sqrt(783) #Asumiremos estas raíces calculadas como las más certeras
raiz_1, raiz_2

(55.98213715926644, 0.017862840733556595)

In [3]:
x1 = 28 + 27.982
x2 = 28 - 27.982

print("Error absoluto raíz 1: ")
print(f"{abs(raiz_1-x1):.4f}")

print("Error absoluto raíz 2:")
print(f"{abs(raiz_2-x2):.4f}")

Error absoluto raíz 1: 
0.0001
Error absoluto raíz 2:
0.0001


In [4]:
print("Error relativo raíz 1: ")
print(f"{abs(raiz_1-x1)/abs(raiz_1):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x2)/abs(raiz_2):.2e}")

Error relativo raíz 1: 
2.45e-06

Error relativo raíz 2: 
7.68e-03


Notamos inmediatamente que el error relativo difiere en un orden de $10^{3}$ entre ambas soluciones. Nos gustaría que esto no fuera así. Para esto revisaremos formas de cómo evitar esto.

### Utilice su conocimiento sobre polinomios de grado 2 para encontrar otra fórmula para calcular $x_2$, la raíz que tiene mayor error relativo.

Tenemos que para polinomios de grado 2 se cumple la siguiente relación:

$$x_1x_2=c$$

Con esto, tenemos lo siguiente:

$$x_2=\frac{c}{x_1}$$

Que para el caso que estudiamos significa que:

$$x_2 = \frac{1}{x_1}$$

El cálculo de $x_2$ por este método es ventajoso ya que el error relativo se acota en términos del error relativo en $x_1$. Veamos esto:

In [5]:
x21 = 1/x1
print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x21):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x21)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
4.38e-08

Error relativo raíz 2: 
2.45e-06


### Revise el valor de $x_2$ y encuentre una forma de representarlo sin usar restas.

Vemos que:

$$\begin{align*}
x_2=
28-\sqrt{783} 
&= \sqrt{784}-\sqrt{783}\\
&=\frac{\sqrt{784}-\sqrt{783}}{\sqrt{784}+\sqrt{783}}(\sqrt{784}+\sqrt{783})\\
&=\frac{784-783}{\sqrt{784}+\sqrt{783}}\\
&=\frac{1}{28+\sqrt{783}} = \frac{1}{x_1}
\end{align*}$$

Es decir, obtenemos la misma formula revisada anteriormente, y ya sabemos como mejora el error relativo obtenido.

### Utilice series de Taylor para aproximar la raíz problemática.

Vemos la función $f(x)=\sqrt{x}$ y su serie de Taylor:

$$f(x+h) = f(x) + f'(x)h + \frac{1}{2}f''(x)h^2+\dots$$

Entonces, tomando la aproximación de primer orden:

$$f(x+h)-f(x) \approx f'(x)h$$

Lo cual, reemplazando con $x=783$ y $h=1$:

$$28-\sqrt{783} \approx \frac{1}{2\sqrt{783}}$$

Para una aproximación de segundo orden:

$$f(x+h)-f(x) \approx f'(x)h + \frac{1}{2}f''(x)h^2$$

Entonces:

$$28-\sqrt{783} \approx \frac{1}{2\sqrt{783}} - \frac{1}{4\cdot783^{3/2}}$$

Veremos como cambia el error relativo con ambas aproximaciones. Notemos que con esta última aproximación hay una resta!

In [6]:
x22 = 0.5/27.982
print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x22):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x22)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
5.79e-06

Error relativo raíz 2: 
3.24e-04


In [7]:
x23 = (0.5/27.982) - (0.25)/(27.982**3)

print("Error absoluto raíz 2: ")
print(f"{abs(raiz_2-x23):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x23)/abs(raiz_2):.2e}")

Error absoluto raíz 2: 
5.62e-06

Error relativo raíz 2: 
3.15e-04


### Escriba una rutina que calcule las raíces de un polinomio de grado 2 con menor error relativo

In [8]:
def calculator(a, b, c, dec=3):
    """
    input:  coeficientes a, b y c de un polinomio
            p(x) = ax^2 + bx + c
    output: raíces x1, x2
    """
    delta = np.around(np.sqrt(b**2 - 4*a*c), decimals=dec)
    x1 = (-b + delta)/(2*a)
    x2 = c/x1
    return x1, x2

In [9]:
x1, x2 = calculator(1, -56, 1, dec=2)

print("Error absoluto raíz 1: ")
print(f"{abs(raiz_1-x1):.2e}")

print("\nError relativo raíz 1: ")
print(f"{abs(raiz_1-x1)/abs(raiz_1):.2e}")

print("\nError absoluto raíz 2:")
print(f"{abs(raiz_2-x2):.2e}")

print("\nError relativo raíz 2: ")
print(f"{abs(raiz_2-x2)/abs(raiz_2):.2e}")

Error absoluto raíz 1: 
2.14e-03

Error relativo raíz 1: 
3.82e-05

Error absoluto raíz 2:
6.82e-07

Error relativo raíz 2: 
3.82e-05


## Problema2

Integral equation visto en pizarra.

## Problema 4

$$\left(\begin{array}{cccccc} 
    a_{11} & a_{12} & a_{13} &0&0&0\\
     a_{21} & a_{22} & a_{23} &a_{24}&0&0\\
    0&a_{32}&a_{33}&a_{34}&a_{35}&0\\
    0&0&a_{43}&a_{44}&a_{45}&a_{46}\\
    0&0&0&a_{54}&a_{55}&a_{56}\\
    0&0&0&0&a_{65}&a_{66}
\end{array}\right) \mapsto \left(\begin{array}{cccccc}
*&*&a_{13}&a_{24}&a_{35}&a_{46}\\
*&a_{12}&a_{23}&a_{34}&a_{45}&a_{56}\\
a_{11}&a_{22}&a_{33}&a_{44}&a_{55}&a_{66}\\
a_{21}&a_{32}&a_{43}&a_{54}&a_{65}&*\\

\end{array}\right)$$



In [10]:
def BandStorage_Gaxpy(ABand,p,q,y,x):
    """
    input:  ABand = matriz de almacenamiento en band form
            p = número de subdiagonales
            q = número de superdiagonales
            y = vector y
            x = vector x
    output: y overwritten with A*x + y
    """
    
    # arreglar con estudiantes :D 
    n = len(y)
    for j in range(1,n+1):
        alpha1 = max(1, j - q) 
        alpha2 = min(n, j + p) 
        beta1 = max(1, q - j + 2) 
        beta2 = max(1, q - j + 2) + min(n, j + p) - max(1, j - q) 

        alpha1 = alpha1 -1
        beta1 = beta1 - 1
        alpha2 = alpha2 
        beta2 = beta2
        y[alpha1:alpha2] += ABand[beta1:beta2, j-1] * x[j-1]

    return y

y = np.zeros(6)
x = np.ones(6)
A = np.array([[1,2,3,0,0,0],[4,5,6,7,0,0],[0,9,10,11,12,0],[0,0,13,14,15,16],[0,0,0,18,19,20],[0,0,0,0,23,24]])
# print(A)
ABand = np.array([[0,0,3,7,12,16],[0,2,6,11,15,20],[1,5,10,14,19,24],[4,9,13,18,23,0]])
print(ABand)
print(y+np.dot(A,x))
print(BandStorage_Gaxpy(ABand,1,2,y,x))

[[ 0  0  3  7 12 16]
 [ 0  2  6 11 15 20]
 [ 1  5 10 14 19 24]
 [ 4  9 13 18 23  0]]
[ 6. 22. 42. 58. 57. 47.]
[ 6. 22. 42. 58. 57. 47.]
